name: PR Preview

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  preview:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run quality checks
      run: |
        npm run lint
        npm run type-check

    - name: Build application
      run: npm run build
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        OPENAI_API_KEY: dummy_key_for_preview
        DATABASE_URL: postgresql://dummy:dummy@localhost:5432/dummy
        NEXTAUTH_URL: http://localhost:3000
        NEXTAUTH_SECRET: dummy_secret_for_preview

    - name: Deploy Preview to Vercel
      uses: vercel/action@v1
      id: vercel-deploy
      with:
        vercel-token: ${{ secrets.VERCEL_TOKEN }}
        vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
        vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NEXTAUTH_URL: https://preview.vercel.app
        NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}

    - name: Comment PR with preview URL
      uses: actions/github-script@v7
      if: always()
      with:
        script: |
          const deploymentUrl = '${{ steps.vercel-deploy.outputs.preview-url }}';
          const comment = deploymentUrl 
            ? `🚀 **Preview deployment ready!**\n\n📝 Preview URL: ${deploymentUrl}\n\n✅ Build completed successfully.`
            : `❌ **Preview deployment failed**\n\nPlease check the build logs for more details.`;
          
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: comment
          });